import { User, Post, Notification, Channel, Message, DMConversation, DMMessage } from './types';

export const currentUser: User = {
  id: 'u0',
  username: 'lake',
  displayName: 'Lake',
  bio: 'Builder. Keyboard enthusiast. #TypeScript #React',
  isPrivate: false,
  followersCount: 142,
  followingCount: 87,
  postsCount: 203,
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: 'u1',
    username: 'tsuru',
    displayName: 'Tsuru Dev',
    bio: 'Rust & systems programming',
    isPrivate: false,
    followersCount: 891,
    followingCount: 234,
    postsCount: 512,
    isFollowing: true,
  },
  {
    id: 'u2',
    username: 'akari_codes',
    displayName: 'Akari',
    bio: 'Frontend wizard. CSS is magic.',
    isPrivate: false,
    followersCount: 1203,
    followingCount: 445,
    postsCount: 678,
    isFollowing: true,
  },
  {
    id: 'u3',
    username: 'zen_backend',
    displayName: 'Zen',
    bio: 'Go, PostgreSQL, k8s. Keep it simple.',
    isPrivate: true,
    followersCount: 320,
    followingCount: 98,
    postsCount: 180,
    isFollowing: false,
  },
  {
    id: 'u4',
    username: 'nova_ml',
    displayName: 'Nova ML',
    bio: 'LLMs, embeddings, inference optimization',
    isPrivate: false,
    followersCount: 4200,
    followingCount: 201,
    postsCount: 934,
    isFollowing: true,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'p1',
    author: mockUsers[1],
    content: `Rustでゼロコストな非同期ランタイムを自作してみた。Tokioを使わずにepollを直接叩くやつ。\n\n\`\`\`rust\nuse std::os::unix::io::RawFd;\nuse std::collections::HashMap;\n\nstruct Reactor {\n    epoll_fd: RawFd,\n    wakers: HashMap<RawFd, Waker>,\n}\n\nimpl Reactor {\n    fn new() -> Self {\n        let epoll_fd = unsafe { libc::epoll_create1(0) };\n        Reactor { epoll_fd, wakers: HashMap::new() }\n    }\n}\n\`\`\`\n\n想像以上にシンプルで驚いた。本番では使わないけど学習コストゼロ。`,
    type: 'article',
    tags: ['Rust', '非同期', 'システムプログラミング'],
    likesCount: 87,
    repliesCount: 12,
    bookmarksCount: 34,
    createdAt: '2026-05-27T10:30:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 'p2',
    author: mockUsers[2],
    content: `TIL: CSS Grid の \`subgrid\` がついに主要ブラウザ全対応になった。\n\nネストしたグリッドでも親のトラックに揃えられるのでレイアウトが劇的にシンプルになる。\n\n\`\`\`css\n.card-grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n}\n\n.card {\n  display: grid;\n  grid-row: span 3;\n  grid-template-rows: subgrid; /* ← これ */\n}\n\`\`\``,
    type: 'info',
    tags: ['CSS', 'Grid', 'フロントエンド'],
    likesCount: 156,
    repliesCount: 8,
    bookmarksCount: 67,
    createdAt: '2026-05-27T09:15:00Z',
    isLiked: true,
    isBookmarked: true,
  },
  {
    id: 'p3',
    author: mockUsers[4],
    content: `質問: LLM推論のバッチサイズ最適化について、実運用でどんな戦略を取ってる？\n\nリクエストを溜めてからバッチ処理するvs連続ストリーミングの使い分けが難しくて。レイテンシとスループットのトレードオフが特に気になってる。\n\n\`\`\`python\n# 今はこんな感じ\nasync def batch_inference(requests: list[str]) -> list[str]:\n    # 50ms待ってバッチ化\n    await asyncio.sleep(0.05)\n    return await model.generate(requests, max_batch_size=32)\n\`\`\``,
    type: 'question',
    tags: ['LLM', 'ML', 'Python', '推論'],
    likesCount: 43,
    repliesCount: 21,
    bookmarksCount: 18,
    createdAt: '2026-05-27T08:00:00Z',
    isLiked: false,
    isBookmarked: false,
    isSolved: false,
  },
  {
    id: 'p4',
    author: mockUsers[3],
    content: `Goのcontext伝播で地味にはまった話。\n\nHTTPハンドラからgoroutineを生やすとき、リクエストのcontextをそのまま渡すとリクエスト完了後にキャンセルされる。\n\n\`\`\`go\n// NG: リクエスト終了でキャンセルされる\ngo doSomething(r.Context())\n\n// OK: 独立したcontext\nctx := context.WithoutCancel(r.Context())\ngo doSomething(ctx)\n\`\`\`\n\n\`context.WithoutCancel\` はGo 1.21から。それ以前は \`context.Background()\` で値だけコピーするヘルパーを自作してた。`,
    type: 'post',
    tags: ['Go', 'context', 'goroutine'],
    likesCount: 234,
    repliesCount: 17,
    bookmarksCount: 89,
    createdAt: '2026-05-26T22:45:00Z',
    isLiked: true,
    isBookmarked: false,
  },
  {
    id: 'p5',
    author: mockUsers[1],
    content: `今週のTIL: SQLの \`EXPLAIN ANALYZE\` の読み方をちゃんと勉強した。\n\nSeq Scan vs Index Scan の判断基準と、Hash Join vs Nested Loop の使い分けがやっと腑に落ちた。\n\n\`\`\`sql\nEXPLAIN ANALYZE\nSELECT u.username, COUNT(p.id) as post_count\nFROM users u\nLEFT JOIN posts p ON p.user_id = u.id\nWHERE u.created_at > NOW() - INTERVAL '30 days'\nGROUP BY u.id;\n\`\`\`\n\nHash Aggregateが出てたらインデックス見直しのサイン。`,
    type: 'info',
    tags: ['SQL', 'PostgreSQL', 'パフォーマンス'],
    likesCount: 112,
    repliesCount: 6,
    bookmarksCount: 45,
    createdAt: '2026-05-26T19:20:00Z',
    isLiked: false,
    isBookmarked: true,
  },
  {
    id: 'p6',
    author: mockUsers[2],
    content: `React 19の \`use()\` フックを実プロジェクトで使い始めた。\n\nSuspenseと組み合わせるとデータフェッチがかなりすっきり書ける。\n\n\`\`\`tsx\nfunction PostDetail({ id }: { id: string }) {\n  const post = use(fetchPost(id)); // Promise渡せる\n  return <article>{post.content}</article>;\n}\n\n// 親でSuspense\n<Suspense fallback={<Skeleton />}>\n  <PostDetail id={postId} />\n</Suspense>\n\`\`\`\n\nuseEffectの呪縛から解放された感がある。`,
    type: 'post',
    tags: ['React', 'TypeScript', 'フロントエンド'],
    likesCount: 189,
    repliesCount: 23,
    bookmarksCount: 76,
    createdAt: '2026-05-26T15:10:00Z',
    isLiked: false,
    isBookmarked: false,
  },
];

export const mockReplies: Post[] = [
  {
    id: 'r1',
    author: mockUsers[3],
    content: `Continuous Batching（vLLMが採用してる方式）が今のベストプラクティスだと思う。固定バッチより効率的。\n\n\`\`\`python\n# vLLM的なアプローチ\nengine = AsyncLLMEngine.from_engine_args(engine_args)\nasync def generate(prompt: str):\n    async for output in engine.generate(prompt, sampling_params, request_id):\n        yield output.outputs[0].text\n\`\`\``,
    type: 'post',
    tags: [],
    likesCount: 28,
    repliesCount: 3,  // has thread replies
    bookmarksCount: 12,
    createdAt: '2026-05-27T08:30:00Z',
    isLiked: false,
    isBookmarked: false,
    parentId: 'p3',
  },
  {
    id: 'r2',
    author: mockUsers[1],
    content: `レイテンシ重視なら動的バッチング（waiting time based）、スループット重視なら静的バッチが良い印象。リクエスト量のプロファイルによるかな。`,
    type: 'post',
    tags: [],
    likesCount: 15,
    repliesCount: 1,
    bookmarksCount: 5,
    createdAt: '2026-05-27T09:00:00Z',
    isLiked: true,
    isBookmarked: false,
    parentId: 'p3',
  },
];

export const mockThreadReplies: Post[] = [
  {
    id: 'tr1',
    author: mockUsers[1],
    content: 'vLLMのContinuous Batchingは確かに良いけど、モデルサイズによってはシンプルなdynamic batchingの方が実装コスト低くて現実的なこともある。\n\n```python\n# シンプルな動的バッチング実装\nasync def dynamic_batch(requests: list[str], max_wait: float = 0.05) -> list[str]:\n    deadline = asyncio.get_event_loop().time() + max_wait\n    while len(requests) < MAX_BATCH_SIZE:\n        remaining = deadline - asyncio.get_event_loop().time()\n        if remaining <= 0:\n            break\n        await asyncio.sleep(min(0.01, remaining))\n    return await model.batch_generate(requests)\n```',
    type: 'post',
    tags: [],
    likesCount: 12,
    repliesCount: 1,
    bookmarksCount: 3,
    createdAt: '2026-05-27T08:45:00Z',
    isLiked: false,
    isBookmarked: false,
    parentId: 'r1',
  },
  {
    id: 'tr2',
    author: currentUser,
    content: '実際に試した結果、50ms waiting timeで固定バッチよりスループット1.8倍になった。ただしp99レイテンシは少し悪化した。トレードオフをどう設定するかはユースケース次第だね。',
    type: 'post',
    tags: [],
    likesCount: 8,
    repliesCount: 0,
    bookmarksCount: 2,
    createdAt: '2026-05-27T09:10:00Z',
    isLiked: false,
    isBookmarked: false,
    parentId: 'r1',
  },
  {
    id: 'tr3',
    author: mockUsers[4],
    content: '@lake それはかなり良い数字。モデルは何を使ってる？Llama系？',
    type: 'post',
    tags: [],
    likesCount: 4,
    repliesCount: 0,
    bookmarksCount: 0,
    createdAt: '2026-05-27T09:20:00Z',
    isLiked: true,
    isBookmarked: false,
    parentId: 'r1',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    from: mockUsers[1],
    post: mockPosts[3],
    createdAt: '2026-05-27T11:00:00Z',
    read: false,
  },
  {
    id: 'n2',
    type: 'reply',
    from: mockUsers[2],
    post: mockPosts[0],
    createdAt: '2026-05-27T10:45:00Z',
    read: false,
  },
  {
    id: 'n3',
    type: 'follow',
    from: mockUsers[4],
    createdAt: '2026-05-27T09:30:00Z',
    read: true,
  },
];

export const mockChannels: Channel[] = [
  { id: 'c1', name: 'general', description: '雑談・なんでも', unreadCount: 3, lastMessage: 'Next.js 16でてるじゃん' },
  { id: 'c2', name: 'javascript', description: 'JS/TS全般', unreadCount: 0, lastMessage: 'ESModulesの話' },
  { id: 'c3', name: 'help', description: '質問・サポート', unreadCount: 7, lastMessage: 'async/awaitで困ってる' },
  { id: 'c4', name: 'rust', description: 'Rust言語', unreadCount: 0, lastMessage: 'ownership難しい' },
  { id: 'c5', name: 'ml-research', description: 'ML・AI研究', unreadCount: 2, lastMessage: 'Gemini 3出た' },
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    author: mockUsers[2],
    content: 'Next.js 16でてるじゃん。App Routerの安定性かなり上がったらしい',
    channelId: 'c1',
    createdAt: '2026-05-27T11:20:00Z',
  },
  {
    id: 'm2',
    author: mockUsers[1],
    content: 'マジか。PPRとかどうなったんだろ',
    channelId: 'c1',
    createdAt: '2026-05-27T11:21:00Z',
  },
  {
    id: 'm3',
    author: currentUser,
    content: 'changelog読んだけどStreaming SSRの改善が大きそう',
    channelId: 'c1',
    createdAt: '2026-05-27T11:22:00Z',
  },
  {
    id: 'm4',
    author: mockUsers[3],
    content: 'Rustチームはそういうの関係ないからのんびりしてる',
    channelId: 'c1',
    createdAt: '2026-05-27T11:23:00Z',
  },
];

export const mockDMConversations: DMConversation[] = [
  {
    id: 'dm1',
    participants: [mockUsers[1]],
    isGroup: false,
    unreadCount: 2,
    lastMessage: 'あの件、確認しておきます',
    lastMessageAt: '2026-05-27T11:10:00Z',
  },
  {
    id: 'dm2',
    participants: [mockUsers[2]],
    isGroup: false,
    unreadCount: 0,
    lastMessage: 'ありがとう！',
    lastMessageAt: '2026-05-27T09:45:00Z',
  },
  {
    id: 'dm3',
    participants: [mockUsers[1], mockUsers[3], mockUsers[4]],
    isGroup: true,
    groupName: 'バックエンド勉強会',
    unreadCount: 5,
    lastMessage: 'DBのインデックス設計について話したい',
    lastMessageAt: '2026-05-27T10:30:00Z',
  },
  {
    id: 'dm4',
    participants: [mockUsers[2], mockUsers[4]],
    isGroup: true,
    groupName: 'フロントチーム',
    unreadCount: 0,
    lastMessage: 'React 19移行どう？',
    lastMessageAt: '2026-05-26T18:00:00Z',
  },
];

export const mockDMMessages: DMMessage[] = [
  {
    id: 'dm-m1',
    author: mockUsers[1],
    content: 'あの件どうなった？',
    conversationId: 'dm1',
    createdAt: '2026-05-27T11:05:00Z',
  },
  {
    id: 'dm-m2',
    author: currentUser,
    content: '今確認してるところ。もう少し待って',
    conversationId: 'dm1',
    createdAt: '2026-05-27T11:07:00Z',
  },
  {
    id: 'dm-m3',
    author: mockUsers[1],
    content: 'あの件、確認しておきます',
    conversationId: 'dm1',
    createdAt: '2026-05-27T11:10:00Z',
  },
  {
    id: 'dm-m4',
    author: currentUser,
    content: 'CSS Gridのsubgrid見た？かなり便利そう',
    conversationId: 'dm2',
    createdAt: '2026-05-27T09:40:00Z',
  },
  {
    id: 'dm-m5',
    author: mockUsers[2],
    content: 'ありがとう！',
    conversationId: 'dm2',
    createdAt: '2026-05-27T09:45:00Z',
  },
  {
    id: 'dm-m6',
    author: mockUsers[3],
    content: 'DBのインデックス設計について話したい',
    conversationId: 'dm3',
    createdAt: '2026-05-27T10:30:00Z',
  },
  {
    id: 'dm-m7',
    author: mockUsers[4],
    content: 'いいね。複合インデックスの話？',
    conversationId: 'dm3',
    createdAt: '2026-05-27T10:31:00Z',
  },
];

export const trendingTags = [
  { name: 'TypeScript', count: 234 },
  { name: 'Rust', count: 189 },
  { name: 'LLM', count: 156 },
  { name: 'Go', count: 143 },
  { name: 'React', count: 128 },
  { name: 'PostgreSQL', count: 97 },
  { name: 'Docker', count: 86 },
];
